### ISSUE TITLE
Can the log be saved to a file?

### ISSUE THREAD

**Issue by XTeam-Wing** [charmbracelet/log#10]

**Comment by gozeloglu** [comment]
I just checked the repository and I saw that there is an option for custom `io.Writer` in [here](https://github.com/charmbracelet/log/blob/main/options.go#L7). So, maybe you can pass `io.Writer` by creating from [`bufio`](https://gobyexample.com/writing-files#:~:text=w%20%3A%3D%20bufio.NewWriter(f)).

**Comment by XTeam-Wing** [comment]
thx
