### ISSUE TITLE
No color outputs in docker compose

### ISSUE THREAD

**Issue by mpiorowski** [charmbracelet/log#138]
**Describe the bug**
No color outputs in when running go app in docker compose

![image](https://github.com/user-attachments/assets/a89bdff2-1805-48a4-bdf8-fbe9f0db0ff6)

**Comment by mpiorowski** [comment]
That's my current setup:
```
func InitLogger() {
	var level log.Level
	if LOG_LEVEL == "info" {
		level = log.InfoLevel
	} else {
		level = log.DebugLevel
	}

	logger := log.NewWithOptions(os.Stderr, log.Options{
		ReportCaller:    true,
		ReportTimestamp: true,
		TimeFormat:      time.Kitchen,
		Level:           level,
	})
	slog.SetDefault(slog.New(logger))
}
```

**Comment by aymanbagabas** [comment]
How are you running your image? You need to use `docker run -it <image>` for an interactive TTY container.

**Comment by mpiorowski** [comment]
@aymanbagabas  I run the docker compose with -it:
![image](https://github.com/user-attachments/assets/f5c0480f-787b-42c5-baed-89118c3276d0)

Still not working:
![image](https://github.com/user-attachments/assets/c8a4d171-6ba3-4fe9-9159-f3579aa0fe97)

**Comment by aymanbagabas** [comment]
What's your `$TERM` inside the docker? Usually it defaults to `TERM=xterm` which indicates no colors. Try `docker run -e TERM=xterm-256color -e COLORTERM=truecolor -it <image>`

**Comment by mpiorowski** [comment]
Yep, tty: true + this setup helped :)

![image](https://github.com/user-attachments/assets/9dbef247-3921-41e4-a467-15f43c51bcc6)

thanks!
