### ISSUE TITLE
Light color theme?

### ISSUE THREAD

**Issue by jabbalaci** [charmbracelet/log#16]
I belong to the minority who prefers light terminal background color. Do you have a light theme too? It would be nice if we could choose between a dark and a light color theme easily.

**Comment by aymanbagabas** [comment]
hey @jabbalaci 
Yes, we do! Log uses [Lipgloss](https://github.com/charmbracelet/lipgloss) to automatically detect background color. You can customize and adapt the default colors to your liking. Refer to [styles.go](https://github.com/charmbracelet/log/blob/main/styles.go) for more info.

These are the default colors on a light background:
![image](https://user-images.githubusercontent.com/3187948/220935208-8c181c37-760e-4e8d-a3cf-71efaee5ad0c.png)

**Comment by jabbalaci** [comment]
Excellent, thank you! Please mention in the README that you have light theme support too.
