### ISSUE TITLE
Sublogger with prefix?

### ISSUE THREAD

**Issue by tmm1** [charmbracelet/log#36]
I would like to be able to set some options on the default logger (like timestamp format, loglevel), then create sub-loggers which inherit those settings but have their own prefixes.

Right now it seems the only way to create a sub-logger is `With()` which adds key/value pairs but in my case I don't have key/value pairs to add I just want a new prefix.

WDYT about adding a new `WithPrefix()`?

**Comment by aymanbagabas** [comment]
You could use `SetPrefix()` on the sub-logger.
```go
sub := log.With()
sub.SetPrefix("myapp")
...
sub.Info("hello world")
```

**Comment by tmm1** [comment]
Yep that works, thanks!

I would still like to see a convenience wrapper to make it a one liner..

```go
log.WithPrefix("myapp").Info("hello world")
```
