### ISSUE TITLE
No colored output in docker logs

### ISSUE THREAD

**Issue by zekroTJA** [charmbracelet/log#37]
I am using this logger in an application which runs in a docker container, but the printed output in the logs is not colored, what kind of defeats the point. Is there a way how to fix this?

**Comment by aymanbagabas** [comment]
Could you try running your docker container with [`-it`](https://docs.docker.com/engine/reference/commandline/run/#name)?

**Comment by zekroTJA** [comment]
> Could you try running your docker container with [-it](https://docs.docker.com/engine/reference/commandline/run/#name)?

Actually I tested around with it in a container running with the `-it` flags.

This is the code snippet.
```go
package main

import "fmt"
import "github.com/charmbracelet/lipgloss"
import "github.com/charmbracelet/log"

func main() {
  p := lipgloss.NewStyle().Foreground(lipgloss.CompleteColor{TrueColor: "#0000FF", ANSI256: "86", ANSI: "5"}).Render("Foo")
  fmt.Println(p)

  log.Info("Hello World!")

  fmt.Println("\x1b[38;5;201mHello\x1b[0m")
}
```

And this is the result in the container:
![image](https://user-images.githubusercontent.com/16734205/222546860-b8e53c87-396c-4688-aa86-483b4cf5846f.png)

And natively it looks just like expected.
![image](https://user-images.githubusercontent.com/16734205/222547007-14ad54bb-83b6-47f9-925b-97f426f0fb2b.png)

**Comment by zekroTJA** [comment]
Yep, that fixed the issue. Thank you very much for your fast help. <3

**Comment by shellwhale** [comment]
How did you fix that issue exactly? Because it's still happening for me, even when setting a color profile 

```
package main
import (
	"github.com/charmbracelet/log"
    "github.com/muesli/termenv"
    "github.com/charmbracelet/lipgloss"
)

func main() {
    lipgloss.SetColorProfile(termenv.TrueColor)
    log.Info("test")
}
```
