### ISSUE TITLE
How to handle `\t`?

### ISSUE THREAD

**Issue by Dentrax** [charmbracelet/log#46]
Actual:

![Screenshot 2023-03-12 at 21 25 04](https://user-images.githubusercontent.com/16493751/224564618-65051c8b-23c9-4fe0-b28f-50e5f3bf12e1.png)

Expected is: (without `\t`s)
```bash
﻿multierror
  error=
  │ 3 errors occurred:
  │ * foo
  │ * bar
  │ * baz
```

Here is minimal reproducible Go snippet:

```go
package main

import (
	"fmt"
	"github.com/charmbracelet/log"
	"github.com/hashicorp/go-multierror"
)

func main() {
	err := fmt.Errorf("foo")
	err = multierror.Append(err, fmt.Errorf("bar"), fmt.Errorf("baz"))
	log.New().Print("multierror", "error", err.Error())
}
```

```go
strings.ReplaceAll(err.Error(), "\t", "")
```

Fixes the issue but I'm curious if `logger` should handle `\t`, `\n` etc. values. Any ideas?

**Comment by aymanbagabas** [comment]
Log is designed to escape any value characters. Since you're using multierror, I'd suggest splitting the errors and adding them as key/value pairs `err1`, `err2`, etc...
Another option would be to use the "message" to pass the errors. 

```go
package main

import (
	"fmt"
	"os"

	"github.com/charmbracelet/log"
	"github.com/hashicorp/go-multierror"
)

func main() {
	err := fmt.Errorf("foo")
	err = multierror.Append(err, fmt.Errorf("bar"), fmt.Errorf("baz"))
	log.New(os.Stderr).Print(err)
}
```

```
3 errors occurred:
	* foo
	* bar
	* baz
	
```

You could log a message before the multierror message to give more context. You could also use the new Printf style funcs to format the errors the way you like.

```go
package main

import (
	"fmt"

	"github.com/charmbracelet/log"
	"github.com/hashicorp/go-multierror"
)

func main() {
	err := multierror.Append(fmt.Errorf("foo"), fmt.Errorf("bar"), fmt.Errorf("baz"))
	log.Print("multierror:")
	log.Print(err)
	errs := err.WrappedErrors()
	log.Printf("%d errors occurred: %+v", len(errs), errs)
}

```

```
2009/11/10 23:00:00 multierror:
2009/11/10 23:00:00 3 errors occurred:
	* foo
	* bar
	* baz


2009/11/10 23:00:00 3 errors occurred: [foo bar baz]
```

Let me know if this helps :)

**Comment by Dentrax** [comment]
Thank you for clarification, this is really helpful!

**Comment by aymanbagabas** [comment]
> Thank you for clarification, this is really helpful!

Feel free to close this if it resolves your issue.
