### ISSUE TITLE
Wrong API 

### ISSUE THREAD

**Issue by oslyak** [charmbracelet/log#47]
Why API in on the README page does not match with the real API???

![1](https://user-images.githubusercontent.com/3803656/225281356-605d1a12-2183-4272-a52b-b23e5cc3a9d7.png)

**Comment by aymanbagabas** [comment]
Hi @oslyak. Thank you for reporting this. We were preparing for a new release with some breaking changes. The new API is now part of [v0.2.0](https://github.com/charmbracelet/log/releases/tag/v0.2.0). You can always find the correct documentations at https://pkg.go.dev/github.com/charmbracelet/log.
