### ISSUE TITLE
Error output and standard output should be separated

### ISSUE THREAD

**Issue by fandujar** [charmbracelet/log#51]
Default output (if no output is informed) is defined as stderr:

https://github.com/charmbracelet/log/blob/89a61d46421faf8c869bbf5c44375febaf106068/logger.go#L242-L256

As a good practice, stdout and stderr should be separated so we can pipe the output to the correct destination.

As an example, you can reproduce this behavior using the following:

```bash
# it should pipe only standard output
./example 1> /dev/null

# it should pipe only error output
./example 2> /dev/null
```

**Comment by aymanbagabas** [comment]
This is the current behavior, the default output _is_ stderr. You can set the output in your program to stdout, a file, or any io.Writer.

**Comment by fandujar** [comment]
@aymanbagabas Does it make sense opening a enhancement issue to create a method that allows user to set both standard output and error output?

**Comment by aymanbagabas** [comment]
Log only supports one output. It uses stderr by default. You can create two Log instances each with its own output and settings.
