### ISSUE TITLE
Unable to use "prefix" as logger key

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/log#61]
Hi, 
For some reason I can't use "prefix" as a key when logging something.

```go
package main

import "github.com/charmbracelet/log"

func main() {
	log.Info("Test", "prefix", "test", "suffix", "test")
}
```

When executed:
![demo](https://github.com/charmbracelet/log/assets/26183582/b90cac8a-4f3a-4ae7-81f9-06c6cc31d240)

Is "prefix" somehow a reserved keyword?

**Comment by aymanbagabas** [comment]
Hi @jon4hz, correct, `prefix` and similar other words are considered reserved see [`formatter.go`](https://github.com/charmbracelet/log/blob/c39b96e3a02315b0a5b4810d24b8ae85d1a53b6f/formatter.go#L16)

**Comment by jon4hz** [comment]
noted, thx for the answer
