### ISSUE TITLE
multiwriter file logging

### ISSUE THREAD

**Issue by yusufaine** [charmbracelet/log#77]
I'm glad that #71 fixed the colour issue, but was wondering if there was a way to allow logging to a file without said colour tags.

I currently have a logger setup like this:

```go
writers := []io.Writer{os.Stderr}
if (logFile != "") {
    // open file
    writers = append(writers, fd)
}

ml := log.NewWithOptions(io.MultiWriter(wrs...), loggerOpts)
ml.SetColorProfile(termenv.TrueColor)
log.SetDefault(ml)
```

but the log file outputs as

```bash
[1;38;5;86mINFO[0m [2m<crawler/crawler.go:68>[0m visiting [2mdepth[0m[2m=[0m0 [2mlink[0m[2m=[0mhttps://example.com
[1;38;5;86mINFO[0m [2m<crawler/crawler.go:68>[0m visiting [2mdepth[0m[2m=[0m1 [2mlink[0m[2m=[0mhttps://www.iana.org/domains/example
[1;38;5;86mINFO[0m [2m<crawler/crawler.go:68>[0m visiting [2mdepth[0m[2m=[0m2 
```
![image](https://github.com/charmbracelet/log/assets/29030941/5c92bdb0-a522-4913-88bf-177c5bacf602)

**Comment by aymanbagabas** [comment]
Hi @yusufaine, Log is meant to be used with one writer. Using `SetColorProfile` overrides the detected profile for the writer. Thus, using an `io.MultiWriter` will always disable the colors since the writer is not a terminal. Instead, you could wrap Log in a custom type that takes multiple writers and assigns each to its logger instance. 

With this, if io.Writer is not a terminal, colors will be disabled.

```go
type MultiLogger struct {
  writers []io.Writer
  loggers []*log.Logger
}

func NewMultiLogger(wrs ...io.Writer) *MultiLogger {
  ml := new(MultiLogger)
  ml.writers = make([]io.Writer, len(wrs))
  ml.loggers = make([]*log.Logger, len(wrs))
  for i, w := range wrs {
    ml.writer[i] = w
    ml.loggers[i] = log.New(w)
  }
  return ml
}

func (ml *MultiLogger) Info(msg any, kvs ...any) {
  for _, l := range ml.loggers {
    l.Info(msg, kvs...)
  }
}

```

**Comment by yusufaine** [comment]
Awesome, I've implemented a similar solution as well, thanks for this!

**Comment by cooperspencer** [comment]
I'd have a question for this specific approach, how'd you handle a `log.Fatal` here?

Because if I run a `log.Fatal` it would only write to one `io.Writer`

**Comment by yusufaine** [comment]
@cooperspencer A similar approach can be taken, iterate over the loggers with error severity and `os.Exit(1)` after all the iterations, similar to how it's already implemented. 

https://github.com/charmbracelet/log/blob/main/logger.go#L371

**Comment by eparisot-mitsa** [comment]
Another issue I got with this method is I got no timestamp on begining of lines neither in file or stdout...
I tryed to use NewWithOptions and provide a TimeFormat but no luck...

`ml.loggers[i] = log.NewWithOptions(w, log.Options{
			TimeFormat: time.Kitchen,
		})`

any idea ?
