### ISSUE TITLE
Support x/exp/slog

### ISSUE THREAD

**Issue by carlmjohnson** [charmbracelet/log#8]
See this comment on Reddit for an explanation of the issue: https://reddit.com/r/golang/comments/11844t9/_/j9fkpn5/

This API is already very close to slog, so it can probably just wrap it as a new slog.Handler.

**Comment by ManveerBhullar** [comment]
Slog has is gonna be in 1.21 , slated for August.
https://tip.golang.org/doc/go1.21

**Comment by jamietanna** [comment]
I've made an update to #13 in https://github.com/charmbracelet/log/pull/74 to amend it to work with the Go 1.21 :rocket:
