### ISSUE TITLE
Woudn't be nice if this lib is wrapped as a shell tool, and can be installed with i.e. brew ? (Like gum)

### ISSUE THREAD

**Issue by dzonekl** [charmbracelet/log#86]
Woudn't be nice if this lib is wrapped as a shell tool, and can be installed with i.e. brew ? (Like gum)

**Comment by maaslalani** [comment]
Hey @dzonekl, that's a great idea! We (@aymanbagabas) just added `log` to `gum` and it will be available in the next release.

https://github.com/charmbracelet/gum#log

If you want to try it out now, you can install `gum` on the latest `main`:

```bash
go install github.com/charmbracelet/gum@main
```

**Comment by dzonekl** [comment]
Great ! thanks guys !
