### ISSUE TITLE
Support slog.Leveler

### ISSUE THREAD

**Issue by jaredallard** [charmbracelet/log#98]
It'd be nice if one could use `slog.Leveler` to control the log level of the logger!

**Comment by aymanbagabas** [comment]
Since Log is just a handler to log/slog, you can dynamically change the Log instance level using `SetLevel(level)`

**Comment by Amejonah1200** [comment]
There is one feature I like with Leveler  it is because when it is cloned with `.With(...)`, only the reference gets cloned and so, using LevelVar, it is possible to change the level of all loggers at once.
