### ISSUE TITLE
Debug method not work in go 1.21

### ISSUE THREAD

**Issue by IgorDePaula** [charmbracelet/log#99]
In none of example the Debug method works =/

![Captura de tela de 2023-12-07 21-54-24](https://github.com/charmbracelet/log/assets/2833993/2645feb7-184a-4bce-ac75-5f3c95044095)
![Captura de tela de 2023-12-07 21-54-13](https://github.com/charmbracelet/log/assets/2833993/84ebb4bf-4407-477a-8884-43115a1c92ef)
![Captura de tela de 2023-12-07 21-53-49](https://github.com/charmbracelet/log/assets/2833993/1295eb22-2936-4ad2-92ef-9e76083a117e)
![Captura de tela de 2023-12-07 21-53-45](https://github.com/charmbracelet/log/assets/2833993/bb600086-7f0a-4041-8a93-069f12f8d165)
![Captura de tela de 2023-12-07 21-53-22](https://github.com/charmbracelet/log/assets/2833993/1e990d47-4dae-4b4c-bbdd-eb9bf6fc55c4)
![Captura de tela de 2023-12-07 21-53-15](https://github.com/charmbracelet/log/assets/2833993/0d5544c8-f7e9-4d50-bb14-9518482b6974)
![Captura de tela de 2023-12-07 21-52-37](https://github.com/charmbracelet/log/assets/2833993/5f229f3e-9643-4cd8-926c-3c20d2bff7dd)
![Captura de tela de 2023-12-07 21-52-16](https://github.com/charmbracelet/log/assets/2833993/c36294d4-9b6a-46ff-9291-fd598bca63f2)

**Comment by h0rv** [comment]
Hi Igor, the default log level is set to `Info`, try adding the following line at the beginning of the functions: `log.SetLevel(log.DebugLevel)`.

**Comment by IgorDePaula** [comment]
> Hi @IgorDePaula, the default log level is set to `Info`, try adding the following line at the beginning of the functions: `log.SetLevel(log.DebugLevel)`.

Oh, ok, I will try. Thank you very much.

**Comment by IgorDePaula** [comment]
![image](https://github.com/charmbracelet/log/assets/2833993/dc9621cf-a0a2-4531-a3e4-5009f3272846)


It Works, Thank you very much for your attention.
